# ASSIGNMENT 01 (50 Numpy function)

# Name: Memoona Maqsood

# Roll no. = PIAIC109709

In [5]:
# 1) Array
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [6]:
a.dtype

dtype('int32')

In [7]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [14]:
# 2) Create an array of all zeros
c = np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# 3) Create an array of all ones
d = np.ones((4,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# 4) Create a constant array
e = np.full((3,2), 5)
e

array([[5, 5],
       [5, 5],
       [5, 5]])

In [22]:
# 5) Create a 2x2 identity matrix
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [24]:
# 6) Create an array filled with random values
g = np.random.random((4,3))
g

array([[0.37724829, 0.31229465, 0.13808746],
       [0.76336089, 0.41141434, 0.63690359],
       [0.86192075, 0.64357559, 0.16828452],
       [0.40191783, 0.01671693, 0.34647681]])

In [29]:
# 7) add
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [28]:
# 8) Subtract
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]


In [30]:
# 9) Multiply
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]


In [31]:
# 10) Divide
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [32]:
# 11) Square root
print(np.sqrt(x, y))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [33]:
# 12) transposing a matrix
x = np.array([[1,2], [3,4]])
print(x)

[[1 2]
 [3 4]]


In [34]:
print(x.T)  

[[1 3]
 [2 4]]


In [42]:
# 13) Reshape
v = np.array([1,2,3,4]) 
print(v.reshape(2,2))

[[1 2]
 [3 4]]


In [46]:
# 14) Array splitting
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
newarr = np.array_split(arr, 5)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]


In [49]:
# 15) Generate Random Number
from numpy import random
x = random.randint(100)
print(x)

72


In [53]:
# 15) Generate Random Float
a = random.rand()
print(a)

0.8315772883538097


In [54]:
# 16) Choice
x = random.choice([32, 50, 17, 89])
print(x)

17


In [55]:
# 17) Shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [58]:
# 18) Coping array and making changes in original array and displaying both the arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 75
print(arr)

[75  2  3  4  5]


In [59]:
print(x)

[1 2 3 4 5]


In [60]:
# 19) view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 75
print(arr)

[75  2  3  4  5]


In [61]:
print(x)

[75  2  3  4  5]


In [62]:
# 20) round
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.round_(in_array)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]


In [63]:
# 21) exp function
in_array = [1, 3, 5]
print ("Input array : ", in_array)
 
out_array = np.exp(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5]
Output array :  [  2.71828183  20.08553692 148.4131591 ]


In [64]:
# 22) log function
in_array = [1, 3, 5, 2**8]
print ("Input array : ", in_array)
 
out_array = np.log(in_array)
print ("Output array : ", out_array)

Input array :  [1, 3, 5, 256]
Output array :  [0.         1.09861229 1.60943791 5.54517744]


In [65]:
# 23) reciprocal function
in_num = 2.0
print ("Input  number : ", in_num)
 
out_num = np.reciprocal(in_num)
print ("Output number : ", out_num)

Input  number :  2.0
Output number :  0.5


In [66]:
# 24) isreal function
import numpy as geek 
print("Is Real : ", geek.isreal([1+1j, 0j]), "\n")
print("Is Real : ", geek.isreal([1, 0]), "\n")

Is Real :  [False  True] 

Is Real :  [ True  True] 



In [67]:
# 25) Conjugate function
in_complx1 = 2+4j
out_complx1 = np.conj(in_complx1)
print ("Output conjugated complex number of  2+4j : ", out_complx1)

Output conjugated complex number of  2+4j :  (2-4j)


In [68]:
# 26) cube root function
arr1 = [1, 27000, 64, -1000]
print ("cbrt Value of arr1 : \n", np.cbrt(arr1))

cbrt Value of arr1 : 
 [  1.  30.   4. -10.]


In [70]:
# 27) clip function
in_array = [1, 2, 3, 4, 5, 6, 7, 8 ]
print ("Input array : ", in_array)
 
out_array = np.clip(in_array, a_min = 3, a_max = 6)
print ("Output array : ", out_array)

Input array :  [1, 2, 3, 4, 5, 6, 7, 8]
Output array :  [3 3 3 4 5 6 6 6]


In [72]:
# 28) linspace function
a = np.linspace(2,7,10)
a

array([2.        , 2.55555556, 3.11111111, 3.66666667, 4.22222222,
       4.77777778, 5.33333333, 5.88888889, 6.44444444, 7.        ])

In [75]:
# 29) min function
b = np.array([9,1,5])
b.min()

1

In [76]:
# 30) max function
b = np.array([9,1,5])
b.max()

9

In [78]:
# 31) Standard Deviation function
m = np.array([(2, 4, 6), (7, 9, 10)])
m.std()

2.748737083745107

In [82]:
# 32) Vertical Stacking Function
a = np.array([(1,2,3), (4,5,6)])
b =np.array([(7,8,9), (10,11,12)])
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
# 33) Horizontal Stacking Function
a = np.array([(1,2,3), (4,5,6)])
b =np.array([(7,8,9), (10,11,12)])
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [84]:
# 34) Ravel Function
a = np.array([(1,2,3), (4,5,6)])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [86]:
# 35) arrange function
np.arange(5,50,6)

array([ 5, 11, 17, 23, 29, 35, 41, 47])

In [89]:
# 36) Sin Function
np.sin(90)

0.8939966636005579

In [90]:
# 37) Cos Function
np.cos(90)

-0.4480736161291701

In [92]:
# 38) tan Function
np.tan(45)

1.6197751905438615

In [95]:
# 39) lowest common multiple function
np.lcm(3,10)

30

In [94]:
# 40) Greatest common divisor
np.gcd(3,11)

1

In [96]:
# 41) negative function
np.negative(5)

-5

In [97]:
# 42) positive function
np.positive(-75)

-75

In [99]:
# 43) power function
x = [1.0, 2.0, 3.0, 4.0, 5.0]
np.power(x, 3)

array([  1.,   8.,  27.,  64., 125.])

In [101]:
# 44) rint function
in_array = [.5, 1.5, 2.5, 3.5, 5.5, 10.1] 
print ("Input array : \n", in_array) 
  
rintoff_values = np.rint(in_array) 
print ("\nRounded values : \n", rintoff_values) 

Input array : 
 [0.5, 1.5, 2.5, 3.5, 5.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  6. 10.]


In [105]:
# 45) sort function
x = np.array([6,8,1,2,4,9])
np.sort(x)

array([1, 2, 4, 6, 8, 9])

In [106]:
# 46) Cross function
x = [1, 2, 3]
y = [4, 5, 6]
np.cross(x, y)

array([-3,  6, -3])

In [108]:
# 47) prod function
np.prod([6,5])

30

In [109]:
# 48) real function
a = np.array([1+2j, 3+4j, 5+6j])
a.real

array([1., 3., 5.])

In [111]:
# 49) angle function
np.angle([1.0, 1.0j, 1+1j]) #in radian

array([0.        , 1.57079633, 0.78539816])

In [114]:
# 50) imaginary function
a = np.array([1+2j, 3+4j, 5+6j])
np.imag(a)

array([2., 4., 6.])